services:
  tf:
    image: hashicorp/terraform:1.9
    working_dir: /workspace/tf
    entrypoint: ["terraform"]
    volumes:
      - ./:/workspace                           # monta tu repo
      - /var/run/docker.sock:/var/run/docker.sock  # ¡clave! TF hablará con Docker
